# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceD2',
            fields=[
                ('InOutDSeq', models.AutoField(primary_key=True, serialize=False, verbose_name='입출고DSeq')),
                ('InOutSubSeq', models.IntegerField(verbose_name='입출고순번')),
                ('Qty', models.FloatField(blank=True, null=True, verbose_name='수량')),
                ('InOutSubDivSeq', models.IntegerField(choices=[(1101, '내수구매'), (2101, '정상판매'), (2102, '판매반품'), (2201, '계산서'), (3101, '판촉사용'), (3102, '재고손실')], verbose_name='입출고구분항목')),
                ('Remark', models.CharField(blank=True, max_length=100, verbose_name='비고')),
                ('UnitSeq', models.IntegerField(blank=True, null=True, verbose_name='사원')),
                ('Price', models.FloatField(blank=True, null=True, verbose_name='단가')),
                ('Amt', models.FloatField(blank=True, verbose_name='금액')),
                ('BasePrice', models.FloatField(blank=True, verbose_name='기준단가')),
                ('BaseAmt', models.FloatField(blank=True, null=True, verbose_name='기준금액')),
                ('InOutSeq', models.ForeignKey(db_column='InOutSeq', on_delete=django.db.models.deletion.CASCADE, to='QS.InvoiceM', verbose_name='입출고Seq')),
                ('ItemSeq', models.ForeignKey(db_column='ItemSeq', on_delete=django.db.models.deletion.CASCADE, to='QS.Item', verbose_name='품목')),
            ],
            options={
                'verbose_name': '거래명세품목',
                'verbose_name_plural': '거래명세품목',
                'db_table': 'tinoutd',
            },
        ),
        migrations.AlterUniqueTogether(
            name='invoiced2',
            unique_together=set([('InOutSeq', 'InOutSubSeq')]),
        ),
    ]
