# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QS', '0002_auto_20170919_1739'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoiced2',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='invoiced2',
            name='InOutSeq',
        ),
        migrations.RemoveField(
            model_name='invoiced2',
            name='ItemSeq',
        ),
        migrations.DeleteModel(
            name='InvoiceD2',
        ),
    ]
